# IntelliJ Platform Artifacts Repositories -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = com.github.nguyenphuc22.androidpackagerenamer
pluginName = Android-Package-Renamer
pluginRepositoryUrl = https://github.com/nguyenphuc22/Android-Package-Renamer
# SemVer format -> https://semver.org
pluginVersion = 1.1.0

# Supported build number ranges and IntelliJ Platform versions -> https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
pluginSinceBuild = 233
pluginUntilBuild = 262.*

# IntelliJ Platform Properties -> https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-extension.html
platformType = IC
platformVersion = 2024.1

# Gradle Releases -> https://github.com/gradle/gradle/releases
gradleVersion = 9.7.0

# Opt-out flag for bundling Kotlin standard library -> https://plugins.jetbrains.com/docs/intellij/kotlin.html#kotlin-standard-library
# suppress inspection "UnusedProperty"
kotlin.stdlib.default.dependency = false
